/*
* generated by Xtext
*/
package org.telcodev.dsl.ui.outline;

import org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider;

/**
 * customization of the default outline structure
 * 
 */
public class DimeOutlineTreeProvider extends DefaultOutlineTreeProvider {
	
}
