/*
 * generated by Xtext
 */
package org.telcodev.dsl.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class DimeExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return org.telcodev.dsl.ui.internal.DimeActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return org.telcodev.dsl.ui.internal.DimeActivator.getInstance().getInjector("org.telcodev.dsl.Dime");
	}
	
}
