/*
 * generated by Xtext
 */
package org.telcodev.dsl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class DimeUiModule extends org.telcodev.dsl.ui.AbstractDimeUiModule {
	public DimeUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
