/*
* generated by Xtext
*/
package org.telcodev.dsl.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.telcodev.dsl.services.DimeGrammarAccess;

public class DimeParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private DimeGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected org.telcodev.dsl.parser.antlr.internal.InternalDimeParser createParser(XtextTokenStream stream) {
		return new org.telcodev.dsl.parser.antlr.internal.InternalDimeParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "Document";
	}
	
	public DimeGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(DimeGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
