/*
* generated by Xtext
*/
package org.telcodev.dsl.ui.contentassist;

import org.telcodev.dsl.ui.contentassist.AbstractDimeProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class DimeProposalProvider extends AbstractDimeProposalProvider {

}
