/*
 * generated by Xtext
 */
package org.telcodev.dsl;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class DimeRuntimeModule extends org.telcodev.dsl.AbstractDimeRuntimeModule {

}
