/*
* generated by Xtext
*/
package org.telcodev.dsl;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class DimeUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return org.telcodev.dsl.ui.internal.DimeActivator.getInstance().getInjector("org.telcodev.dsl.Dime");
	}
	
}
